#!/usr/bin/env python3
"""Interactive physical-calibration assistant for first-time builders."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path
from typing import Any

import yaml  # type: ignore[import-untyped]

from satellite1_ultra.configuration import validate_physical_calibration

ROOT = Path(__file__).resolve().parents[1]
CALIBRATION_FILE = ROOT / "config" / "physical_calibration.yaml"


def _number(prompt: str, default: float, minimum: float, maximum: float) -> float:
    while True:
        raw = input(f"{prompt} [{default:g}]: ").strip()
        try:
            value = default if not raw else float(raw)
        except ValueError:
            print("Enter a decimal number.")
            continue
        if minimum <= value <= maximum:
            return value
        print(f"Enter a value from {minimum:g} to {maximum:g}.")


def _choice(prompt: str, choices: tuple[float, ...], default: float) -> float:
    values = ", ".join(f"{value:g}" for value in choices)
    while True:
        raw = input(f"{prompt} ({values}) [{default:g}]: ").strip()
        try:
            value = default if not raw else float(raw)
        except ValueError:
            print("Enter one of the listed values.")
            continue
        if value in choices:
            return value
        print("Enter one of the listed values.")


def _load() -> dict[str, Any]:
    with CALIBRATION_FILE.open(encoding="utf-8") as source:
        values = yaml.safe_load(source)
    if not isinstance(values, dict):
        raise ValueError(f"{CALIBRATION_FILE} must contain a YAML mapping")
    validate_physical_calibration(values)
    return values


def _write(values: dict[str, Any]) -> None:
    validate_physical_calibration(values)
    lines = [
        "# Satellite1 Ultra physical calibration input",
        "# Generated by scripts/calibrate.py. Units are millimetres; scale",
        "# corrections are fractions (0.001 = +0.1%).",
        "",
    ]
    for key, value in values.items():
        lines.append(f"{key}: {value}")
    temporary = CALIBRATION_FILE.with_suffix(".yaml.tmp")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    temporary.replace(CALIBRATION_FILE)


def _run_wizard() -> dict[str, Any]:
    print("Satellite1 Ultra calibration")
    print("Use the printed labels and diagrams in CALIBRATION_GUIDE.pdf.")
    print("Press Enter to accept a nominal value. No full-size part is built yet.\n")

    xy_measured = _number("Measured XY 110.60 recess width (mm)", 110.60, 107.0, 114.0)
    z_measured = _number("Measured Z 3.00 coupon thickness (mm)", 3.00, 2.90, 3.10)
    clearance = _choice(
        "Smallest M3 CLEAR hole that passes an M3 screw freely (mm)",
        (3.4, 3.5, 3.6),
        3.4,
    )
    insert_bore = _choice(
        "INSERT BORE that seats the insert square without cracking (mm)",
        (4.0, 4.1, 4.2, 4.3),
        4.2,
    )
    driver_offset = _number(
        "Driver cutout correction; positive enlarges the opening (mm)",
        0.0,
        -1.0,
        1.0,
    )
    passive_offset = _number(
        "Passive-radiator cutout correction; positive enlarges the opening (mm)",
        0.0,
        -1.0,
        1.0,
    )
    cable_offset = _number(
        "Cable-passage correction; positive enlarges the opening (mm)",
        0.0,
        -0.8,
        0.8,
    )
    gasket_sheet = _number("Measured uncompressed gasket thickness (mm)", 2.0, 1.5, 2.5)
    compressed_gasket = _number(
        "Measured tightened gasket gap (mm)",
        0.75 * gasket_sheet,
        0.55 * gasket_sheet,
        0.85 * gasket_sheet,
    )
    driver_flange = _number("Measured Dayton ND91-4 flange thickness (mm)", 3.0, 2.0, 5.0)
    passive_flange = _number("Measured SB12PACR-00 flange thickness (mm)", 4.0, 2.0, 6.0)

    return {
        "xy_scale_correction_fraction": round(110.60 / xy_measured - 1.0, 7),
        "z_scale_correction_fraction": round(3.00 / z_measured - 1.0, 7),
        "fastener_clearance_diameter_offset_mm": round(clearance - 3.4, 3),
        "insert_bore_diameter_offset_mm": round(insert_bore - 4.2, 3),
        "driver_cutout_diameter_offset_mm": round(driver_offset, 3),
        "passive_radiator_cutout_diameter_offset_mm": round(passive_offset, 3),
        "cable_passage_diameter_offset_mm": round(cable_offset, 3),
        "gasket_sheet_thickness_mm": round(gasket_sheet, 3),
        "gasket_compressed_thickness_offset_mm": round(compressed_gasket - 0.75 * gasket_sheet, 3),
        "active_driver_flange_thickness_mm": round(driver_flange, 3),
        "passive_radiator_flange_thickness_mm": round(passive_flange, 3),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate the existing calibration file without changing it",
    )
    parser.add_argument(
        "--no-build",
        action="store_true",
        help="save values without running make calibrated-release",
    )
    args = parser.parse_args()

    if args.check:
        _load()
        print(f"Calibration input is valid: {CALIBRATION_FILE.relative_to(ROOT)}")
        return

    values = _run_wizard()
    validate_physical_calibration(values)
    print("\nCalculated calibration values:")
    for key, value in values.items():
        print(f"  {key}: {value}")
    answer = input("\nSave these values? [y/N]: ").strip().lower()
    if answer not in {"y", "yes"}:
        print("Canceled; no files changed.")
        return
    _write(values)
    print(f"Saved {CALIBRATION_FILE.relative_to(ROOT)}")
    if not args.no_build:
        subprocess.run(["make", "calibrated-release"], cwd=ROOT, check=True)


if __name__ == "__main__":
    main()
